
export const ANIMAL_LIST = [
    { name: '골든리트리버', name_en: 'Golden Retriever', themeColor: '#F39C12', themeGradient: 'from-[#F39C12] to-[#F1C40F]' },
    { name: '비글', name_en: 'Beagle', themeColor: '#F39C12', themeGradient: 'from-[#E67E22] to-[#F39C12]' },
    { name: '웰시코기', name_en: 'Welsh Corgi', themeColor: '#F39C12', themeGradient: 'from-[#D35400] to-[#E67E22]' },
    { name: '허스키', name_en: 'Husky', themeColor: '#3498DB', themeGradient: 'from-[#3498DB] to-[#5DADE2]' },
    { name: '포메라니안', name_en: 'Pomeranian', themeColor: '#FAD7A0', themeGradient: 'from-[#FAD7A0] to-[#F5B041]' },
    { name: '치와와', name_en: 'Chihuahua', themeColor: '#AEB6BF', themeGradient: 'from-[#AEB6BF] to-[#85929E]' },
    { name: '보더콜리', name_en: 'Border Collie', themeColor: '#2C3E50', themeGradient: 'from-[#2C3E50] to-[#566573]' },
    { name: '래브라도', name_en: 'Labrador', themeColor: '#F1C40F', themeGradient: 'from-[#F1C40F] to-[#F39C12]' },
    { name: '러시안블루', name_en: 'Russian Blue', themeColor: '#9B59B6', themeGradient: 'from-[#9B59B6] to-[#8E44AD]' },
    { name: '페르시안', name_en: 'Persian', themeColor: '#E8DAEF', themeGradient: 'from-[#E8DAEF] to-[#D2B4DE]' },
    { name: '브리티시숏헤어', name_en: 'British Shorthair', themeColor: '#BDC3C7', themeGradient: 'from-[#BDC3C7] to-[#A6ACAF]' },
    { name: '스코티시폴드', name_en: 'Scottish Fold', themeColor: '#F5CBA7', themeGradient: 'from-[#F5CBA7] to-[#EDBB99]' },
    { name: '샴', name_en: 'Siamese', themeColor: '#85C1E9', themeGradient: 'from-[#85C1E9] to-[#AED6F1]' },
    { name: '메인쿤', name_en: 'Maine Coon', themeColor: '#E59866', themeGradient: 'from-[#E59866] to-[#DC7633]' },
    { name: '벵갈', name_en: 'Bengal', themeColor: '#F5B041', themeGradient: 'from-[#F5B041] to-[#F39C12]' },
    { name: '터키시앙고라', name_en: 'Turkish Angora', themeColor: '#FEF9E7', themeGradient: 'from-[#FEF9E7] to-[#F8F9F9]' },
    { name: '여우', name_en: 'Fox', themeColor: '#E67E22', themeGradient: 'from-[#E67E22] to-[#D35400]' },
    { name: '늑대', name_en: 'Wolf', themeColor: '#95A5A6', themeGradient: 'from-[#95A5A6] to-[#7F8C8D]' },
    { name: '사자', name_en: 'Lion', themeColor: '#F1C40F', themeGradient: 'from-[#F1C40F] to-[#D4AC0D]' },
    { name: '호랑이', name_en: 'Tiger', themeColor: '#E74C3C', themeGradient: 'from-[#E74C3C] to-[#C0392B]' },
    { name: '표범', name_en: 'Leopard', themeColor: '#F7DC6F', themeGradient: 'from-[#F7DC6F] to-[#F1C40F]' },
    { name: '치타', name_en: 'Cheetah', themeColor: '#F9E79F', themeGradient: 'from-[#F9E79F] to-[#F7DC6F]' },
    { name: '하이에나', name_en: 'Hyena', themeColor: '#BCAAA4', themeGradient: 'from-[#BCAAA4] to-[#A1887F]' },
    { name: '자칼', name_en: 'Jackal', themeColor: '#D7CCC8', themeGradient: 'from-[#D7CCC8] to-[#BCAAA4]' },
    { name: '토끼', name_en: 'Rabbit', themeColor: '#FFB6C1', themeGradient: 'from-[#FFB6C1] to-[#FFC0CB]' },
    { name: '사슴', name_en: 'Deer', themeColor: '#C39BD3', themeGradient: 'from-[#C39BD3] to-[#BB8FCE]' },
    { name: '기린', name_en: 'Giraffe', themeColor: '#F8C471', themeGradient: 'from-[#F8C471] to-[#F5B041]' },
    { name: '알파카', name_en: 'Alpaca', themeColor: '#EBDEF0', themeGradient: 'from-[#EBDEF0] to-[#E8DAEF]' },
    { name: '양', name_en: 'Sheep', themeColor: '#E5E7E9', themeGradient: 'from-[#E5E7E9] to-[#D7DBDD]' },
    { name: '염소', name_en: 'Goat', themeColor: '#CCD1D1', themeGradient: 'from-[#CCD1D1] to-[#B2BABB]' },
];

export const ANALYSIS_MESSAGES = [
    "AI가 당신과 닮은 동물을 찾고 있어요...",
    "얼굴형 분석 완료",
    "눈매 특징 파악 완료",
    "코 모양 분석 완료",
    "입술 특징 분석 중...",
    "동물상 데이터와 매칭 중...",
    "잠시만요! 거의 다 됐어요",
];
